import { TODAY, addDays } from '../utils/date'

export const categories = [
  'Health',
  'Lifestyle',
  'Productivity',
  'Wellness',
  'Finances',
  'Faith',
  'Business',
]

export const defaultData = {
  tasks: [
    {
      id: 1,
      title: 'Morning workout',
      completed: true,
      category: 'Health',
      date: TODAY,
      time: '06:30',
      linkedGoalId: 1,
      linkedProjectId: null,
      priority: 'High',
      recurrence: 'weekly',
    },
    {
      id: 2,
      title: 'Review budget and spending',
      completed: false,
      category: 'Finances',
      date: TODAY,
      time: '19:00',
      linkedGoalId: 3,
      linkedProjectId: null,
      priority: 'Medium',
      recurrence: 'weekly',
    },
    {
      id: 3,
      title: 'Draft section for TB manual',
      completed: false,
      category: 'Productivity',
      date: addDays(TODAY, 1),
      time: '09:30',
      linkedGoalId: 2,
      linkedProjectId: 1,
      priority: 'High',
      recurrence: 'none',
    },
    {
      id: 4,
      title: 'Prayer and journaling',
      completed: true,
      category: 'Wellness',
      date: TODAY,
      time: '05:45',
      linkedGoalId: 4,
      linkedProjectId: null,
      priority: 'Low',
      recurrence: 'daily',
    },
    {
      id: 5,
      title: 'Call insurance office',
      completed: false,
      category: 'Lifestyle',
      date: addDays(TODAY, -1),
      time: '',
      linkedGoalId: null,
      linkedProjectId: null,
      priority: 'Medium',
      recurrence: 'none',
    },
  ],
  goals: [
    { id: 1, title: 'Train 4x per week', category: 'Health', targetDate: addDays(TODAY, 45), why: 'Keep health moving forward' },
    { id: 2, title: 'Complete TB manual', category: 'Business', targetDate: addDays(TODAY, 120), why: 'Finish the business foundation asset' },
    { id: 3, title: 'Stay under weekly spending target', category: 'Finances', targetDate: addDays(TODAY, 6), why: 'Improve financial awareness' },
    { id: 4, title: 'Finish Bible in a year plan', category: 'Faith', targetDate: `${new Date().getFullYear()}-12-31`, why: 'Stay consistent spiritually' },
  ],
  projects: [
    { id: 1, title: 'TB Manual', goalId: 2, dueDate: addDays(TODAY, 120), status: 'Active', description: 'Build out the manual chapters and organization.' },
    { id: 2, title: 'Planner Web App', goalId: null, dueDate: addDays(TODAY, 60), status: 'Active', description: 'Turn the planner into a clean app beta.' },
  ],
  expenses: [
    { id: 1, amount: 72, category: 'Food', date: addDays(TODAY, -1), note: 'Groceries' },
    { id: 2, amount: 135, category: 'Bills', date: TODAY, note: 'Water + utilities' },
    { id: 3, amount: 40, category: 'Business', date: TODAY, note: 'App domain tools' },
  ],
  notes: [
    { id: 1, title: 'Planner ideas', content: 'Keep navigation simple and reduce clutter.', linkedType: 'project', linkedId: 2 },
    { id: 2, title: 'Finance focus', content: 'Weekly spending needs a visual summary and upcoming bills list.', linkedType: 'goal', linkedId: 3 },
  ],
  events: [
    { id: 1, title: 'Client appointment', date: TODAY, startTime: '11:00', endTime: '12:00', category: 'Business' },
    { id: 2, title: 'Church small group', date: TODAY, startTime: '18:30', endTime: '20:00', category: 'Faith' },
  ],
  habits: [
    { id: 1, title: 'Workout', category: 'Health' },
    { id: 2, title: 'Budget check', category: 'Finances' },
    { id: 3, title: 'Prayer', category: 'Wellness' },
  ],
  habitLogs: [
    { id: 1, habitId: 1, date: TODAY, completed: true },
    { id: 2, habitId: 2, date: TODAY, completed: false },
    { id: 3, habitId: 3, date: TODAY, completed: true },
  ],
  budget: { weeklyTarget: 350 },
  profile: {
    displayName: 'Anthony',
    timezone: 'America/Chicago',
    plannerMode: 'Balanced',
  },
  settings: {
    onboardingComplete: false,
    showCompletedTasks: true,
    compactCalendar: false,
  },
}
